from typing import Any

LOG: Any

def get_pkg_unique_identifier(): ...
def get_cache_dir(): ...

class DiskCache:
    enabled: Any = ...
    cache_dir: Any = ...
    lock_timeout: Any = ...
    file_ext: str = ...
    def __init__(self, cache_dir: Any, lock_timeout: int = ...) -> None: ...
    def get(self, namespace: Any, key: Any): ...
    def set(self, namespace: Any, key: Any, value: Any): ...
    def clear(self) -> None: ...
    def run_and_cache(self, func: Any, namespace: Any, kwargs: Any, hashed_argnames: Any): ...
    def cached_fetch_url(self, session: Any, url: Any, timeout: Any): ...
