from typing import Any, Optional

LOG: Any
PUBLIC_SUFFIX_RE: Any
PUBLIC_PRIVATE_SUFFIX_SEPARATOR: str

class SuffixListNotFound(LookupError): ...

def find_first_response(cache: Any, urls: Any, cache_fetch_timeout: Optional[Any] = ...): ...
def extract_tlds_from_suffix_list(suffix_list_text: Any): ...
def get_suffix_lists(cache: Any, urls: Any, cache_fetch_timeout: Any, fallback_to_snapshot: Any): ...
