from typing import Any, Optional

class InstanceHeader:
    header: Any = ...
    def __init__(self, header: Optional[Any] = ...) -> None: ...
    def get_header_label_at(self, header_index: int = ...): ...
    def get_info(self): ...
