from skmultiflow.core import BaseSKMObject as BaseSKMObject
from typing import Any, Optional

class Pipeline(BaseSKMObject):
    steps: Any = ...
    active: bool = ...
    def __init__(self, steps: Any) -> None: ...
    def predict(self, X: Any): ...
    def fit(self, X: Any, y: Any): ...
    def partial_fit(self, X: Any, y: Any, classes: Optional[Any] = ...): ...
    def partial_fit_predict(self, X: Any, y: Any): ...
    def partial_fit_transform(self, X: Any, y: Optional[Any] = ...) -> None: ...
    def named_steps(self): ...
    def get_info(self): ...
