from skmultiflow.trees.split_criterion import VarianceReductionSplitCriterion as VarianceReductionSplitCriterion
from typing import Any

class IntraClusterVarianceReductionSplitCriterion(VarianceReductionSplitCriterion):
    def __init__(self) -> None: ...
    def get_merit_of_split(self, pre_split_dist: Any, post_split_dist: Any): ...
    @staticmethod
    def compute_SD(dist: Any): ...
