import pprint
from . import is_scalar_nan as is_scalar_nan
from ..core.base import BaseEstimator as BaseEstimator
from typing import Any, Optional

class KeyValTuple(tuple): ...
class KeyValTupleParam(KeyValTuple): ...

class _EstimatorPrettyPrinter(pprint.PrettyPrinter):
    n_max_elements_to_show: Any = ...
    def __init__(self, indent: int = ..., width: int = ..., depth: Optional[Any] = ..., stream: Optional[Any] = ..., *, compact: bool = ..., indent_at_name: bool = ..., n_max_elements_to_show: Optional[Any] = ...) -> None: ...
    def format(self, object: Any, context: Any, maxlevels: Any, level: Any): ...
