from typing import Any, Optional

def clean_header(base_file: Any, new_file: Optional[Any] = ..., ignore_char: str = ...) -> None: ...

class RemoveHeader:
    base_file: Any = ...
    new_file: Any = ...
    ignore_char: Any = ...
    def __init__(self, base_file: Any, new_file: Optional[Any] = ..., ignore_char: str = ...) -> None: ...
    def configure(self, base_file: Any, new_file: Any, ignore_char: Any) -> None: ...
    def get_info(self): ...
    def get_class_type(self): ...
    def clean_file(self) -> None: ...
