from typing import Any

SQRTH: float
MAXLOG: float

def normal_probability(a: Any): ...
def error_function(x: Any): ...
def error_function_complemented(a: Any): ...
def pol_evl(x: Any, coef: Any, N: Any): ...
def p1_evl(x: Any, coef: Any, N: Any): ...
