from typing import Any, Optional

INDENT: Any

def safe_repr(value: Any): ...
def eq_repr(value: Any, repr: Any = ...): ...
def uniq_stable(elems: Any): ...
def fix_frame_records_filenames(records: Any): ...
def format_records(records: Any): ...
def format_exc(etype: Any, evalue: Any, etb: Any, context: int = ..., tb_offset: int = ...): ...
def format_outer_frames(context: int = ..., stack_start: Optional[Any] = ..., stack_end: Optional[Any] = ..., ignore_ipython: bool = ...): ...
