from typing import Any, Optional

WindowsError = OSError

def disk_used(path: Any): ...
def memstr_to_bytes(text: Any): ...
def mkdirp(d: Any) -> None: ...

RM_SUBDIRS_RETRY_TIME: float
RM_SUBDIRS_N_RETRY: int

def rm_subdirs(path: Any, onerror: Optional[Any] = ...) -> None: ...
def delete_folder(folder_path: Any, onerror: Optional[Any] = ..., allow_non_empty: bool = ...) -> None: ...
