from .logger import pformat as pformat
from typing import Any

full_argspec_fields: str

full_argspec_type: Any
def get_func_code(func: Any): ...
def get_func_name(func: Any, resolv_alias: bool = ..., win_characters: bool = ...): ...
def filter_args(func: Any, ignore_lst: Any, args: Any = ..., kwargs: Any = ...): ...
def format_signature(func: Any, *args: Any, **kwargs: Any): ...
def format_call(func: Any, args: Any, kwargs: Any, object_name: str = ...): ...
