from .disk import mkdirp as mkdirp
from typing import Any, Optional

def format_time(t: Any): ...
def short_format_time(t: Any): ...
def pformat(obj: Any, indent: int = ..., depth: int = ...): ...

class Logger:
    depth: Any = ...
    def __init__(self, depth: int = ...) -> None: ...
    def warn(self, msg: Any) -> None: ...
    def debug(self, msg: Any) -> None: ...
    def format(self, obj: Any, indent: int = ...): ...

class PrintTime:
    last_time: Any = ...
    start_time: Any = ...
    logfile: Any = ...
    def __init__(self, logfile: Optional[Any] = ..., logdir: Optional[Any] = ...) -> None: ...
    def __call__(self, msg: str = ..., total: bool = ...) -> None: ...
