from .numpy_pickle_utils import Unpickler as Unpickler
from typing import Any, Optional

def hex_str(an_int: Any): ...
def asbytes(s: Any): ...
def read_zfile(file_handle: Any): ...
def write_zfile(file_handle: Any, data: Any, compress: int = ...) -> None: ...

class NDArrayWrapper:
    filename: Any = ...
    subclass: Any = ...
    allow_mmap: Any = ...
    def __init__(self, filename: Any, subclass: Any, allow_mmap: bool = ...) -> None: ...
    def read(self, unpickler: Any): ...

class ZNDArrayWrapper(NDArrayWrapper):
    filename: Any = ...
    state: Any = ...
    init_args: Any = ...
    def __init__(self, filename: Any, init_args: Any, state: Any) -> None: ...
    def read(self, unpickler: Any): ...

class ZipNumpyUnpickler(Unpickler):
    dispatch: Any = ...
    mmap_mode: Any = ...
    file_handle: Any = ...
    np: Any = ...
    def __init__(self, filename: Any, file_handle: Any, mmap_mode: Optional[Any] = ...) -> None: ...
    def load_build(self) -> None: ...

def load_compatibility(filename: Any): ...
