from abc import ABCMeta, abstractmethod
from typing import Any

class BaseLink(metaclass=ABCMeta):
    @abstractmethod
    def __call__(self, y_pred: Any) -> Any: ...
    @abstractmethod
    def derivative(self, y_pred: Any) -> Any: ...
    @abstractmethod
    def inverse(self, lin_pred: Any) -> Any: ...
    @abstractmethod
    def inverse_derivative(self, lin_pred: Any) -> Any: ...

class IdentityLink(BaseLink):
    def __call__(self, y_pred: Any): ...
    def derivative(self, y_pred: Any): ...
    def inverse(self, lin_pred: Any): ...
    def inverse_derivative(self, lin_pred: Any): ...

class LogLink(BaseLink):
    def __call__(self, y_pred: Any): ...
    def derivative(self, y_pred: Any): ...
    def inverse(self, lin_pred: Any): ...
    def inverse_derivative(self, lin_pred: Any): ...

class LogitLink(BaseLink):
    def __call__(self, y_pred: Any): ...
    def derivative(self, y_pred: Any): ...
    def inverse(self, lin_pred: Any): ...
    def inverse_derivative(self, lin_pred: Any): ...
