from skmultiflow.core import RegressorMixin as RegressorMixin
from skmultiflow.lazy.base_neighbors import BaseNeighbors as BaseNeighbors
from skmultiflow.utils import get_dimensions as get_dimensions
from typing import Any, Optional

class KNNRegressor(BaseNeighbors, RegressorMixin):
    aggregation_method: Any = ...
    def __init__(self, n_neighbors: int = ..., max_window_size: int = ..., leaf_size: int = ..., metric: str = ..., aggregation_method: str = ...) -> None: ...
    def partial_fit(self, X: Any, y: Any, sample_weight: Optional[Any] = ...): ...
    def predict(self, X: Any): ...
    def predict_proba(self, X: Any) -> None: ...
