from skmultiflow.drift_detection import ADWIN as ADWIN
from skmultiflow.lazy import KNNClassifier as KNNClassifier
from skmultiflow.utils.utils import get_dimensions as get_dimensions
from typing import Any, Optional

def KNNAdwin(n_neighbors: int = ..., max_window_size: int = ..., leaf_size: int = ...): ...

class KNNADWINClassifier(KNNClassifier):
    adwin: Any = ...
    def __init__(self, n_neighbors: int = ..., max_window_size: int = ..., leaf_size: int = ..., metric: str = ...) -> None: ...
    def reset(self): ...
    classes: Any = ...
    def partial_fit(self, X: Any, y: Any, classes: Optional[Any] = ..., sample_weight: Optional[Any] = ...): ...
