from typing import Any

class Video:
    embed_type: Any = ...
    provider: Any = ...
    width: Any = ...
    height: Any = ...
    embed_code: Any = ...
    src: Any = ...
    def __init__(self) -> None: ...
