from skmultiflow.trees.attribute_observer import AttributeClassObserver as AttributeClassObserver
from skmultiflow.trees.attribute_split_suggestion import AttributeSplitSuggestion as AttributeSplitSuggestion
from skmultiflow.trees.attribute_test import NominalAttributeBinaryTest as NominalAttributeBinaryTest, NominalAttributeMultiwayTest as NominalAttributeMultiwayTest
from typing import Any

class NominalAttributeRegressionObserver(AttributeClassObserver):
    def __init__(self) -> None: ...
    def observe_attribute_class(self, att_val: Any, target: Any, weight: float = ...) -> None: ...
    def probability_of_attribute_value_given_class(self, att_val: Any, target: Any): ...
    def get_best_evaluated_split_suggestion(self, criterion: Any, pre_split_dist: Any, att_idx: Any, binary_only: Any): ...
