from skmultiflow.rules.base_predicate import Predicate as Predicate
from skmultiflow.trees.attribute_test import InstanceConditionalTest as InstanceConditionalTest
from typing import Any

class NominalAttributeMultiwayTest(InstanceConditionalTest):
    def __init__(self, att_idx: Any, branch_mapping: Any) -> None: ...
    def branch_for_instance(self, X: Any): ...
    @staticmethod
    def max_branches(): ...
    def describe_condition_for_branch(self, branch: Any): ...
    def branch_rule(self, branch: Any): ...
    def get_atts_test_depends_on(self): ...
    def add_new_branch(self, att_val: Any): ...
