from .article import Article as Article
from .configuration import Configuration as Configuration
from .settings import POPULAR_URLS as POPULAR_URLS, TRENDING_URL as TRENDING_URL
from .source import Source as Source
from .utils import extend_config as extend_config, print_available_languages as print_available_languages
from typing import Any

def build(url: Any=..., dry: Any=..., config: Any=..., **kwargs: Any) -> Source: ...
def build_article(url: Any=..., config: Any=..., **kwargs: Any) -> Article: ...
def languages() -> None: ...
def popular_urls(): ...
def hot(): ...
def fulltext(html: Any, language: str = ...): ...
