from .parsers import Parser as Parser
from .text import StopWords as StopWords, StopWordsArabic as StopWordsArabic, StopWordsChinese as StopWordsChinese, StopWordsHindi as StopWordsHindi, StopWordsJapanese as StopWordsJapanese, StopWordsKorean as StopWordsKorean
from typing import Any

log: Any

class Configuration:
    MIN_WORD_COUNT: int = ...
    MIN_SENT_COUNT: int = ...
    MAX_TITLE: int = ...
    MAX_TEXT: int = ...
    MAX_KEYWORDS: int = ...
    MAX_AUTHORS: int = ...
    MAX_SUMMARY: int = ...
    MAX_SUMMARY_SENT: int = ...
    MAX_FILE_MEMO: int = ...
    memoize_articles: bool = ...
    fetch_images: bool = ...
    image_dimension_ration: Any = ...
    follow_meta_refresh: bool = ...
    use_meta_language: bool = ...
    keep_article_html: bool = ...
    http_success_only: bool = ...
    stopwords_class: Any = ...
    browser_user_agent: Any = ...
    headers: Any = ...
    request_timeout: int = ...
    proxies: Any = ...
    number_threads: int = ...
    verbose: bool = ...
    thread_timeout_seconds: int = ...
    def __init__(self) -> None: ...
    def get_language(self): ...
    def del_language(self) -> None: ...
    def set_language(self, language: Any) -> None: ...
    language: Any = ...
    @staticmethod
    def get_stopwords_class(language: Any): ...
    @staticmethod
    def get_parser(): ...

class ArticleConfiguration(Configuration): ...
class SourceConfiguration(Configuration): ...
