from .text import innerTrim as innerTrim
from typing import Any

log: Any

class OutputFormatter:
    top_node: Any = ...
    config: Any = ...
    parser: Any = ...
    language: Any = ...
    stopwords_class: Any = ...
    def __init__(self, config: Any) -> None: ...
    def update_language(self, meta_lang: Any) -> None: ...
    def get_top_node(self): ...
    def get_formatted(self, top_node: Any): ...
    def convert_to_text(self): ...
    def convert_to_html(self): ...
    def add_newline_to_br(self) -> None: ...
    def add_newline_to_li(self) -> None: ...
    def links_to_text(self) -> None: ...
    def remove_negativescores_nodes(self) -> None: ...
    def replace_with_text(self) -> None: ...
    def remove_empty_tags(self) -> None: ...
    def remove_trailing_media_div(self): ...
