from typing import Any

log: Any
PARENT_DIRECTORY: Any
POPULAR_URLS: Any
USERAGENTS: Any
STOPWORDS_DIR: Any
NLP_STOPWORDS_EN: Any
DATA_DIRECTORY: str
TOP_DIRECTORY: Any
LOGFILE: Any
MONITOR_LOGFILE: Any
MEMO_FILE: str
MEMO_DIR: Any
CF_CACHE_DIRECTORY: str
ANCHOR_DIRECTORY: Any
TRENDING_URL: str
