from typing import Any, Optional

log: Any
MAX_FILE_MEMO: int
DATE_REGEX: str
STRICT_DATE_REGEX: Any
ALLOWED_TYPES: Any
GOOD_PATHS: Any
BAD_CHUNKS: Any
BAD_DOMAINS: Any

def remove_args(url: Any, keep_params: Any = ..., frags: bool = ...): ...
def redirect_back(url: Any, source_domain: Any): ...
def prepare_url(url: Any, source_url: Optional[Any] = ...): ...
def valid_url(url: Any, verbose: bool = ..., test: bool = ...): ...
def url_to_filetype(abs_url: Any): ...
def get_domain(abs_url: Any, **kwargs: Any): ...
def get_scheme(abs_url: Any, **kwargs: Any): ...
def get_path(abs_url: Any, **kwargs: Any): ...
def is_abs_url(url: Any): ...
