from typing import Any

class AttributeExpandSuggestion:
    resulting_class_distributions: Any = ...
    merit: Any = ...
    att_idx: Any = ...
    att_val: Any = ...
    operator: Any = ...
    def __init__(self, att_idx: Any, att_val: Any, operator: Any, resulting_class_distributions: Any, merit: Any) -> None: ...
    def num_splits(self): ...
    def resulting_class_distribution_from_split(self, split_idx: Any): ...
