from skmultiflow.trees.split_criterion import SplitCriterion as SplitCriterion
from typing import Any

class FoilGainExpandCriterion(SplitCriterion):
    min_branch_frac_option: Any = ...
    best_idx: int = ...
    class_idx: int = ...
    def __init__(self, min_branch_frac_option: float = ...) -> None: ...
    def get_merit_of_split(self, pre_split_dist: Any, post_split_dist: Any): ...
    def get_range_of_merit(self, pre_split_dist: Any): ... # type: ignore
    def compute_entropy(self, dist: Any): ...
    @staticmethod
    def num_subsets_greater_than_frac(distributions: Any, min_frac: Any): ...
