from skmultiflow.trees.attribute_observer import NominalAttributeRegressionObserver as NominalAttributeRegressionObserver, NumericAttributeRegressionObserver as NumericAttributeRegressionObserver
from skmultiflow.trees.nodes import ActiveLearningNode as ActiveLearningNode
from typing import Any

class ActiveLearningNodeForRegression(ActiveLearningNode):
    def __init__(self, initial_class_observations: Any) -> None: ...
    def learn_from_instance(self, X: Any, y: Any, weight: Any, ht: Any) -> None: ...
    def get_weight_seen(self): ...
    def manage_memory(self, criterion: Any, last_check_ratio: Any, last_check_sdr: Any, last_check_e: Any) -> None: ...
