from skmultiflow.trees.attribute_observer import AttributeClassObserverNull as AttributeClassObserverNull, NominalAttributeClassObserver as NominalAttributeClassObserver, NumericAttributeClassObserverGaussian as NumericAttributeClassObserverGaussian
from skmultiflow.trees.attribute_split_suggestion import AttributeSplitSuggestion as AttributeSplitSuggestion
from skmultiflow.trees.nodes import LearningNode as LearningNode
from typing import Any

class ActiveLearningNode(LearningNode):
    def __init__(self, initial_class_observations: Any) -> None: ...
    def learn_from_instance(self, X: Any, y: Any, weight: Any, ht: Any) -> None: ...
    def get_weight_seen(self): ...
    def get_weight_seen_at_last_split_evaluation(self): ...
    def set_weight_seen_at_last_split_evaluation(self, weight: Any) -> None: ...
    def get_best_split_suggestions(self, criterion: Any, ht: Any): ...
    def disable_attribute(self, att_idx: Any) -> None: ...
    def get_attribute_observers(self): ...
    def set_attribute_observers(self, attribute_observers: Any) -> None: ...
