from skmultiflow.trees.attribute_split_suggestion import AttributeSplitSuggestion as AttributeSplitSuggestion
from skmultiflow.trees.nodes import InactiveLearningNode as InactiveLearningNode
from typing import Any, Optional

class AnyTimeInactiveLearningNode(InactiveLearningNode):
    def __init__(self, initial_class_observations: Optional[Any] = ...) -> None: ...
    def get_best_split_suggestions(self, criterion: Any, ht: Any): ...
    def get_null_split(self, criterion: Any): ...
    @staticmethod
    def count_nodes(): ...
