from skmultiflow.trees.attribute_split_suggestion import AttributeSplitSuggestion as AttributeSplitSuggestion
from skmultiflow.trees.nodes import ActiveLearningNode as ActiveLearningNode
from typing import Any

class AnyTimeActiveLearningNode(ActiveLearningNode):
    def __init__(self, initial_class_observations: Any) -> None: ...
    def get_best_split_suggestions(self, criterion: Any, ht: Any): ...
    def get_null_split(self, criterion: Any): ...
    @staticmethod
    def count_nodes(): ...
