from typing import Any, Optional

class FoundNode:
    node: Any = ...
    parent: Any = ...
    parent_branch: Any = ...
    depth: Any = ...
    def __init__(self, node: Optional[Any] = ..., parent: Optional[Any] = ..., parent_branch: Optional[Any] = ..., depth: Optional[Any] = ...) -> None: ...
