from skmultiflow.trees.nodes import InactiveLearningNode as InactiveLearningNode
from skmultiflow.utils import check_random_state as check_random_state
from typing import Any, Optional

class InactiveLearningNodePerceptron(InactiveLearningNode):
    random_state: Any = ...
    samples_seen: int = ...
    perceptron_weight: Any = ...
    def __init__(self, initial_class_observations: Any, perceptron_node: Optional[Any] = ..., random_state: Optional[Any] = ...) -> None: ...
    def learn_from_instance(self, X: Any, y: Any, weight: Any, rht: Any) -> None: ...
    def update_weights(self, X: Any, y: Any, learning_ratio: Any, ht: Any) -> None: ...
