from skmultiflow.bayes import do_naive_bayes_prediction as do_naive_bayes_prediction
from skmultiflow.trees.nodes import LearningNodeNB as LearningNodeNB
from typing import Any

class LearningNodeNBAdaptive(LearningNodeNB):
    def __init__(self, initial_class_observations: Any) -> None: ...
    def learn_from_instance(self, X: Any, y: Any, weight: Any, ht: Any) -> None: ...
    def get_class_votes(self, X: Any, ht: Any): ...
