from skmultiflow.trees.attribute_observer import NominalAttributeClassObserver as NominalAttributeClassObserver, NumericAttributeClassObserverGaussian as NumericAttributeClassObserverGaussian
from skmultiflow.trees.nodes import ActiveLearningNode as ActiveLearningNode
from skmultiflow.utils import get_dimensions as get_dimensions
from typing import Any, Optional

class RandomLearningNodeClassification(ActiveLearningNode):
    max_features: Any = ...
    list_attributes: Any = ...
    random_state: Any = ...
    def __init__(self, initial_class_observations: Any, max_features: Any, random_state: Optional[Any] = ...) -> None: ...
    def learn_from_instance(self, X: Any, y: Any, weight: Any, ht: Any) -> None: ...
