from skmultiflow.bayes import do_naive_bayes_prediction as do_naive_bayes_prediction
from skmultiflow.trees.nodes import RandomLearningNodeNB as RandomLearningNodeNB
from typing import Any

class RandomLearningNodeNBAdaptive(RandomLearningNodeNB):
    def __init__(self, initial_class_observations: Any, max_features: Any, random_state: Any) -> None: ...
    def learn_from_instance(self, X: Any, y: Any, weight: Any, ht: Any) -> None: ...
    def get_class_votes(self, X: Any, ht: Any): ...
