from skmultiflow.trees.attribute_observer import NominalAttributeRegressionObserver as NominalAttributeRegressionObserver, NumericAttributeRegressionObserver as NumericAttributeRegressionObserver
from skmultiflow.trees.nodes import ActiveLearningNodeForRegression as ActiveLearningNodeForRegression
from skmultiflow.utils import check_random_state as check_random_state, get_dimensions as get_dimensions
from typing import Any, Optional

class RandomLearningNodeForRegression(ActiveLearningNodeForRegression):
    max_features: Any = ...
    list_attributes: Any = ...
    random_state: Any = ...
    def __init__(self, initial_class_observations: Any, max_features: Any, random_state: Optional[Any] = ...) -> None: ...
    def learn_from_instance(self, X: Any, y: Any, weight: Any, rht: Any) -> None: ...
