from skmultiflow.trees.nodes import FoundNode as FoundNode, Node as Node
from typing import Any

class SplitNode(Node):
    def __init__(self, split_test: Any, class_observations: Any) -> None: ...
    def num_children(self): ...
    def get_split_test(self): ...
    def set_child(self, index: Any, node: Any) -> None: ...
    def get_child(self, index: Any): ...
    def instance_child_index(self, X: Any): ...
    @staticmethod
    def is_leaf(): ...
    def filter_instance_to_leaf(self, X: Any, parent: Any, parent_branch: Any): ...
    def subtree_depth(self): ...
    def describe_subtree(self, ht: Any, buffer: Any, indent: int = ...) -> None: ...
    def get_predicate(self, branch: Any): ...
