from skmultiflow.trees.nodes import SSTInactiveLearningNode as SSTInactiveLearningNode
from skmultiflow.utils import get_dimensions as get_dimensions
from typing import Any, Optional

class SSTInactiveLearningNodeAdaptive(SSTInactiveLearningNode):
    fMAE_M: float = ...
    fMAE_P: float = ...
    fMAE_SP: float = ...
    def __init__(self, initial_class_observations: Any, parent_node: Optional[Any] = ..., random_state: Optional[Any] = ...) -> None: ...
    def update_weights(self, X: Any, y: Any, learning_ratio: Any, rht: Any) -> None: ...
