from skmultiflow.trees.nodes import InactiveLearningNodePerceptronMultiTarget as InactiveLearningNodePerceptronMultiTarget
from skmultiflow.utils import get_dimensions as get_dimensions
from typing import Any, Optional

class SSTInactiveLearningNode(InactiveLearningNodePerceptronMultiTarget):
    def __init__(self, initial_class_observations: Any, parent_node: Optional[Any] = ..., random_state: Optional[Any] = ...) -> None: ...
    def learn_from_instance(self, X: Any, y: Any, weight: Any, rht: Any) -> None: ...
    def update_weights(self, X: Any, y: Any, learning_ratio: Any, rht: Any) -> None: ...
    def normalize_perceptron_weights(self) -> None: ...
