from typing import Any, Optional

class AuthError(Exception):
    def __init__(self, msg: Any) -> None: ...

class DocumentNotFound(Exception):
    def __init__(self, msg: Any) -> None: ...

class UnsupportedTypeError(Exception):
    def __init__(self, msg: Any) -> None: ...

class FolderNotFound(Exception):
    def __init__(self, msg: Any) -> None: ...

class ApiError(Exception):
    response: Any = ...
    def __init__(self, msg: Any, response: Optional[Any] = ...) -> None: ...
