from typing import Any

class Meta:
    ID: str = ...
    Version: int = ...
    Message: str = ...
    Success: bool = ...
    BlobURLGet: str = ...
    BlobURLGetExpires: str = ...
    BlobURLPut: str = ...
    BlobURLPutExpires: str = ...
    ModifiedClient: str = ...
    Type: str = ...
    VissibleName: str = ...
    CurrentPage: int = ...
    Bookmarked: bool = ...
    Parent: str = ...
    def __init__(self, **kwargs: Any) -> None: ...
    def to_dict(self) -> dict: ...
