from typing import Any

class BasePlugin:
    def before_write(self, book: Any): ...
    def after_write(self, book: Any): ...
    def before_read(self, book: Any): ...
    def after_read(self, book: Any): ...
    def item_after_read(self, book: Any, item: Any): ...
    def item_before_write(self, book: Any, item: Any): ...
    def html_after_read(self, book: Any, chapter: Any): ...
    def html_before_write(self, book: Any, chapter: Any): ...
