from skmultiflow.utils.utils import *
from skmultiflow.core.base import BaseSKMObject as BaseSKMObject, ClassifierMixin as ClassifierMixin, MetaEstimatorMixin as MetaEstimatorMixin
from skmultiflow.drift_detection import ADWIN as ADWIN
from skmultiflow.lazy import KNNClassifier as KNNClassifier
from skmultiflow.utils import check_random_state as check_random_state
from typing import Any, Optional

def LeverageBagging(base_estimator: Any = ..., n_estimators: int = ..., w: int = ..., delta: float = ..., enable_code_matrix: bool = ..., leverage_algorithm: str = ..., random_state: Optional[Any] = ...): ...

class LeveragingBaggingClassifier(BaseSKMObject, ClassifierMixin, MetaEstimatorMixin):
    ensemble: Any = ...
    adwin_ensemble: Any = ...
    n_detected_changes: Any = ...
    matrix_codes: Any = ...
    classes: Any = ...
    init_matrix_codes: Any = ...
    base_estimator: Any = ...
    n_estimators: Any = ...
    enable_code_matrix: Any = ...
    w: Any = ...
    delta: Any = ...
    leverage_algorithm: Any = ...
    random_state: Any = ...
    def __init__(self, base_estimator: Any = ..., n_estimators: int = ..., w: int = ..., delta: float = ..., enable_code_matrix: bool = ..., leverage_algorithm: str = ..., random_state: Optional[Any] = ...) -> None: ...
    def partial_fit(self, X: Any, y: Any, classes: Optional[Any] = ..., sample_weight: Optional[Any] = ...): ...
    def predict(self, X: Any): ...
    def predict_proba(self, X: Any): ...
    def predict_binary_proba(self, X: Any): ...
    def reset(self): ...
