from skmultiflow.utils.utils import *
from skmultiflow.core import BaseSKMObject as BaseSKMObject, ClassifierMixin as ClassifierMixin, MetaEstimatorMixin as MetaEstimatorMixin
from skmultiflow.lazy import KNNADWINClassifier as KNNADWINClassifier
from skmultiflow.utils import check_random_state as check_random_state
from typing import Any, Optional

def OzaBagging(base_estimator: Any = ..., n_estimators: int = ..., random_state: Optional[Any] = ...): ...

class OzaBaggingClassifier(BaseSKMObject, ClassifierMixin, MetaEstimatorMixin):
    ensemble: Any = ...
    actual_n_estimators: Any = ...
    classes: Any = ...
    base_estimator: Any = ...
    n_estimators: Any = ...
    random_state: Any = ...
    def __init__(self, base_estimator: Any = ..., n_estimators: int = ..., random_state: Optional[Any] = ...) -> None: ...
    def reset(self): ...
    def partial_fit(self, X: Any, y: Any, classes: Optional[Any] = ..., sample_weight: Optional[Any] = ...): ...
    def predict(self, X: Any): ...
    def predict_proba(self, X: Any): ...
