from skmultiflow.utils.utils import *
from skmultiflow.drift_detection import ADWIN as ADWIN
from skmultiflow.lazy import KNNADWINClassifier as KNNADWINClassifier
from skmultiflow.meta import OzaBaggingClassifier as OzaBaggingClassifier
from typing import Any, Optional

def OzaBaggingAdwin(base_estimator: Any = ..., n_estimators: int = ..., random_state: Optional[Any] = ...): ...

class OzaBaggingADWINClassifier(OzaBaggingClassifier):
    adwin_ensemble: Any = ...
    def __init__(self, base_estimator: Any = ..., n_estimators: int = ..., random_state: Optional[Any] = ...) -> None: ...
    def reset(self): ...
    classes: Any = ...
    def partial_fit(self, X: Any, y: Any, classes: Optional[Any] = ..., sample_weight: Optional[Any] = ...): ...
