from skmultiflow.core import BaseSKMObject as BaseSKMObject, MetaEstimatorMixin as MetaEstimatorMixin, MultiOutputMixin as MultiOutputMixin, RegressorMixin as RegressorMixin
from skmultiflow.utils import check_random_state as check_random_state
from typing import Any, Optional

class RegressorChain(BaseSKMObject, RegressorMixin, MetaEstimatorMixin, MultiOutputMixin):
    base_estimator: Any = ...
    order: Any = ...
    random_state: Any = ...
    chain: Any = ...
    ensemble: Any = ...
    L: Any = ...
    def __init__(self, base_estimator: Any = ..., order: Optional[Any] = ..., random_state: Optional[Any] = ...) -> None: ...
    def fit(self, X: Any, y: Any, sample_weight: Optional[Any] = ...): ...
    def partial_fit(self, X: Any, y: Any, sample_weight: Optional[Any] = ...): ...
    def predict(self, X: Any): ...
    def reset(self): ...
    def predict_proba(self, X: Any) -> None: ...
