from abc import ABCMeta, abstractmethod
from skmultiflow.core import BaseSKMObject as BaseSKMObject
from typing import Any, Optional

class StreamTransform(BaseSKMObject, metaclass=ABCMeta):
    def __init__(self) -> None: ...
    @abstractmethod
    def transform(self, X: Any) -> Any: ...
    @abstractmethod
    def partial_fit_transform(self, X: Any, y: Optional[Any] = ...) -> Any: ...
    @abstractmethod
    def partial_fit(self, X: Any, y: Optional[Any] = ...) -> Any: ...
