from skmultiflow.transform.base_transform import StreamTransform as StreamTransform
from skmultiflow.utils import FastBuffer as FastBuffer, get_dimensions as get_dimensions
from typing import Any, Optional

class MissingValuesCleaner(StreamTransform):
    missing_value: Any = ...
    strategy: Any = ...
    window_size: Any = ...
    window: Any = ...
    new_value: Any = ...
    def __init__(self, missing_value: Any = ..., strategy: str = ..., window_size: int = ..., new_value: int = ...) -> None: ...
    def transform(self, X: Any): ...
    def partial_fit_transform(self, X: Any, y: Optional[Any] = ...): ...
    def partial_fit(self, X: Any, y: Optional[Any] = ...): ...
