from skmultiflow.transform.base_transform import StreamTransform as StreamTransform
from skmultiflow.utils import FastBuffer as FastBuffer, get_dimensions as get_dimensions
from typing import Any, Optional

class WindowedMinmaxScaler(StreamTransform):
    window_size: Any = ...
    window: Any = ...
    def __init__(self, window_size: int = ...) -> None: ...
    def transform(self, X: Any): ...
    def partial_fit_transform(self, X: Any, y: Optional[Any] = ...): ...
    def partial_fit(self, X: Any, y: Optional[Any] = ...): ...
