from threading import Thread
from typing import Any

class TqdmSynchronisationWarning(RuntimeWarning): ...

class TMonitor(Thread):
    daemon: bool = ...
    woken: int = ...
    tqdm_cls: Any = ...
    sleep_interval: Any = ...
    was_killed: Any = ...
    def __init__(self, tqdm_cls: Any, sleep_interval: Any) -> None: ...
    def exit(self): ...
    def get_instances(self): ...
    def run(self) -> None: ...
    def report(self): ...
