from .std import tqdm as std_tqdm
from typing import Any

class tqdm_gui(std_tqdm):
    mpl: Any = ...
    plt: Any = ...
    sp: Any = ...
    toolbar: Any = ...
    mininterval: Any = ...
    xdata: Any = ...
    ydata: Any = ...
    zdata: Any = ...
    hspan: Any = ...
    wasion: Any = ...
    ax: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    avg_time: Any = ...
    n: Any = ...
    last_print_t: Any = ...
    miniters: Any = ...
    last_print_n: Any = ...
    def __iter__(self) -> Any: ...
    def update(self, n: int = ...): ...
    disable: bool = ...
    def close(self) -> None: ...
    def display(self) -> None: ... # type: ignore

def tgrange(*args: Any, **kwargs: Any): ...
tqdm = tqdm_gui
trange = tgrange
