import urllib.request
from .urls import convert_to_idn as convert_to_idn
from typing import Any, Optional

ACCEPT_HEADER: str

class _FeedURLHandler(urllib.request.HTTPDigestAuthHandler, urllib.request.HTTPRedirectHandler, urllib.request.HTTPDefaultErrorHandler):
    def http_error_default(self, req: Any, fp: Any, code: Any, msg: Any, headers: Any): ...
    def http_error_301(self, req: Any, fp: Any, code: Any, msg: Any, hdrs: Any): ...
    http_error_300: Any = ...
    http_error_302: Any = ...
    http_error_303: Any = ...
    http_error_307: Any = ...
    def http_error_401(self, req: Any, fp: Any, code: Any, msg: Any, headers: Any): ...

def get(url: Any, etag: Optional[Any] = ..., modified: Optional[Any] = ..., agent: Optional[Any] = ..., referrer: Optional[Any] = ..., handlers: Optional[Any] = ..., request_headers: Optional[Any] = ..., result: Optional[Any] = ...): ...
