from .utils_worker import MonoWorker
from tqdm.auto import tqdm as tqdm_auto
from typing import Any

class TelegramIO(MonoWorker):
    API: str = ...
    token: Any = ...
    chat_id: Any = ...
    session: Any = ...
    text: Any = ...
    message_id: Any = ...
    def __init__(self, token: Any, chat_id: Any) -> None: ...
    def write(self, s: Any): ...

class tqdm_telegram(tqdm_auto):
    tgio: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def display(self, **kwargs: Any) -> None: ...
    def __new__(cls, *args: Any, **kwargs: Any): ...

def ttgrange(*args: Any, **kwargs: Any): ...
tqdm = tqdm_telegram
trange = ttgrange
