from abc import ABCMeta, abstractmethod
from skmultiflow.core import BaseSKMObject as BaseSKMObject
from typing import Any

class BaseDriftDetector(BaseSKMObject, metaclass=ABCMeta):
    estimator_type: str = ...
    in_concept_change: Any = ...
    in_warning_zone: Any = ...
    estimation: Any = ...
    delay: Any = ...
    def __init__(self) -> None: ...
    def reset(self) -> None: ...
    def detected_change(self): ...
    def detected_warning_zone(self): ...
    def get_length_estimation(self): ...
    @abstractmethod
    def add_element(self, input_value: Any) -> Any: ...
