from skmultiflow.drift_detection.base_drift_detector import BaseDriftDetector as BaseDriftDetector
from typing import Any

class DDM(BaseDriftDetector):
    sample_count: Any = ...
    miss_prob: Any = ...
    miss_std: Any = ...
    miss_prob_sd_min: Any = ...
    miss_prob_min: Any = ...
    miss_sd_min: Any = ...
    min_instances: Any = ...
    warning_level: Any = ...
    out_control_level: Any = ...
    def __init__(self, min_num_instances: int = ..., warning_level: float = ..., out_control_level: float = ...) -> None: ...
    def reset(self) -> None: ...
    estimation: Any = ...
    in_concept_change: bool = ...
    in_warning_zone: bool = ...
    delay: int = ...
    def add_element(self, prediction: Any) -> None: ...
