from skmultiflow.drift_detection.base_drift_detector import BaseDriftDetector as BaseDriftDetector
from typing import Any

class EDDM(BaseDriftDetector):
    FDDM_OUTCONTROL: float = ...
    FDDM_WARNING: float = ...
    FDDM_MIN_NUM_INSTANCES: int = ...
    m_num_errors: Any = ...
    m_min_num_errors: int = ...
    m_n: Any = ...
    m_d: Any = ...
    m_lastd: Any = ...
    m_mean: Any = ...
    m_std_temp: Any = ...
    m_m2s_max: Any = ...
    m_last_level: Any = ...
    def __init__(self) -> None: ...
    estimation: float = ...
    def reset(self) -> None: ...
    in_concept_change: bool = ...
    in_warning_zone: bool = ...
    delay: int = ...
    def add_element(self, prediction: Any) -> None: ...
