from math import *
from skmultiflow.drift_detection.base_drift_detector import BaseDriftDetector as BaseDriftDetector
from typing import Any

class HDDM_A(BaseDriftDetector):
    n_min: int = ...
    c_min: int = ...
    total_n: int = ...
    total_c: int = ...
    n_max: int = ...
    c_max: int = ...
    n_estimation: int = ...
    c_estimation: int = ...
    drift_confidence: Any = ...
    warning_confidence: Any = ...
    two_side_option: Any = ...
    def __init__(self, drift_confidence: float = ..., warning_confidence: float = ..., two_side_option: bool = ...) -> None: ...
    in_concept_change: bool = ...
    in_warning_zone: bool = ...
    def add_element(self, prediction: Any) -> None: ...
    def reset(self) -> None: ...
