from skmultiflow.drift_detection.base_drift_detector import BaseDriftDetector as BaseDriftDetector
from typing import Any, Optional

class KSWIN(BaseDriftDetector):
    window_size: Any = ...
    stat_size: Any = ...
    alpha: Any = ...
    change_detected: bool = ...
    p_value: int = ...
    n: int = ...
    window: Any = ...
    def __init__(self, alpha: float = ..., window_size: int = ..., stat_size: int = ..., data: Optional[Any] = ...) -> None: ...
    def add_element(self, input_value: Any) -> None: ...
    def detected_change(self): ...
    def reset(self) -> None: ...
