from skmultiflow.drift_detection.base_drift_detector import BaseDriftDetector as BaseDriftDetector
from typing import Any

class PageHinkley(BaseDriftDetector):
    min_instances: Any = ...
    delta: Any = ...
    threshold: Any = ...
    alpha: Any = ...
    x_mean: Any = ...
    sample_count: Any = ...
    sum: Any = ...
    def __init__(self, min_instances: int = ..., delta: float = ..., threshold: int = ..., alpha: Any = ...) -> None: ...
    def reset(self) -> None: ...
    estimation: Any = ...
    in_concept_change: bool = ...
    in_warning_zone: bool = ...
    delay: int = ...
    def add_element(self, x: Any) -> None: ...
