from skmultiflow.trees import HoeffdingTreeRegressor as HoeffdingTreeRegressor
from skmultiflow.trees.nodes import InactiveLearningNodeForRegression as InactiveLearningNodeForRegression, InactiveLearningNodePerceptron as InactiveLearningNodePerceptron, RandomLearningNodeForRegression as RandomLearningNodeForRegression, RandomLearningNodePerceptron as RandomLearningNodePerceptron
from skmultiflow.utils import check_random_state as check_random_state
from typing import Any, Optional

class ARFHoeffdingTreeRegressor(HoeffdingTreeRegressor):
    max_features: Any = ...
    random_state: Any = ...
    def __init__(self, max_byte_size: int = ..., memory_estimate_period: int = ..., grace_period: int = ..., split_confidence: float = ..., tie_threshold: float = ..., binary_split: bool = ..., stop_mem_management: bool = ..., remove_poor_atts: bool = ..., leaf_prediction: str = ..., no_preprune: bool = ..., nominal_attributes: Optional[Any] = ..., learning_ratio_perceptron: float = ..., learning_ratio_decay: float = ..., learning_ratio_const: bool = ..., max_features: int = ..., random_state: Optional[Any] = ...) -> None: ...
    def reset(self) -> None: ...
    def new_instance(self): ...
