from typing import Any

class AttributeSplitSuggestion:
    split_test: Any = ...
    resulting_class_distributions: Any = ...
    merit: Any = ...
    def __init__(self, split_test: Any, resulting_class_distributions: Any, merit: Any) -> None: ...
    def num_splits(self): ...
    def resulting_class_distribution_from_split(self, split_idx: Any): ...
