from skmultiflow.utils.statistics import normal_probability as normal_probability
from typing import Any

class GaussianEstimator:
    def __init__(self) -> None: ...
    def add_observation(self, value: Any, weight: Any) -> None: ...
    def get_total_weight_observed(self): ...
    def get_mean(self): ...
    def get_std_dev(self): ...
    def get_variance(self): ...
    def probability_density(self, value: Any): ...
    def estimated_weight_lessthan_equalto_greaterthan_value(self, value: Any): ...
