from skmultiflow.trees import HoeffdingTreeRegressor as HoeffdingTreeRegressor
from skmultiflow.trees.nodes import AdaLearningNodeForRegression as AdaLearningNodeForRegression, AdaSplitNodeForRegression as AdaSplitNodeForRegression, InactiveLearningNodeForRegression as InactiveLearningNodeForRegression
from skmultiflow.utils import add_dict_values as add_dict_values
from typing import Any, Optional

def RegressionHAT(max_byte_size: int = ..., memory_estimate_period: int = ..., grace_period: int = ..., split_confidence: float = ..., tie_threshold: float = ..., binary_split: bool = ..., stop_mem_management: bool = ..., remove_poor_atts: bool = ..., leaf_prediction: str = ..., no_preprune: bool = ..., nominal_attributes: Optional[Any] = ..., learning_ratio_perceptron: float = ..., learning_ratio_decay: float = ..., learning_ratio_const: bool = ..., random_state: Optional[Any] = ...): ...

class HoeffdingAdaptiveTreeRegressor(HoeffdingTreeRegressor):
    alternate_trees_cnt: int = ...
    switch_alternate_trees_cnt: int = ...
    pruned_alternate_trees_cnt: int = ...
    def __init__(self, max_byte_size: int = ..., memory_estimate_period: int = ..., grace_period: int = ..., split_confidence: float = ..., tie_threshold: float = ..., binary_split: bool = ..., stop_mem_management: bool = ..., remove_poor_atts: bool = ..., leaf_prediction: str = ..., no_preprune: bool = ..., nominal_attributes: Optional[Any] = ..., learning_ratio_perceptron: float = ..., learning_ratio_decay: float = ..., learning_ratio_const: bool = ..., random_state: Optional[Any] = ...) -> None: ...
    @property
    def leaf_prediction(self): ...
    @leaf_prediction.setter
    def leaf_prediction(self, leaf_prediction: Any) -> None: ...
    def filter_instance_to_leaves(self, X: Any, y: Any, weight: Any, split_parent: Any, parent_branch: Any, update_splitter_counts: Any): ...
    def get_votes_for_instance(self, X: Any): ...
    def new_split_node(self, split_test: Any, class_observations: Any): ...
