from typing import Any

VERSION: Any
ITEM_UNKNOWN: int
ITEM_IMAGE: int
ITEM_STYLE: int
ITEM_SCRIPT: int
ITEM_NAVIGATION: int
ITEM_VECTOR: int
ITEM_FONT: int
ITEM_VIDEO: int
ITEM_AUDIO: int
ITEM_DOCUMENT: int
ITEM_COVER: int
ITEM_SMIL: int
EXTENSIONS: Any
