from typing import Any, Optional

mimetype_initialised: bool

def debug(obj: Any) -> None: ...
def parse_string(s: Any): ...
def parse_html_string(s: Any): ...
def guess_type(extenstion: Any): ...
def create_pagebreak(pageref: Any, label: Optional[Any] = ..., html: bool = ...): ...
def get_headers(elem: Any): ...
def get_pages(item: Any): ...
def get_pages_for_items(items: Any): ...
